-- SYSTEM_parsed.lean
-- Machine-generated Lean 4 encoding of simon.surface_invariants.v1
-- Source: fsl/SYSTEM.yaml (domain_bundles.simon.surface_invariants.v1)
-- Generated by: Phase R-5c, MISSION-LEAN-INV-COMPLETENESS
--
-- Regenerate whenever fsl/SYSTEM.yaml invariants change:
--   python3 -c "
--     import yaml
--     d = yaml.safe_load(open('fsl/SYSTEM.yaml'))
--     syms = d['domain_bundles']['simon.surface_invariants.v1']['symbols']
--     for s in syms:
--         name = s.get('name') or s.get('symbol','?')
--         vs = s.get('violation_sort','')
--         g = s.get('guards','')
--         print(f'  mk \"{name}\" \"{vs}\" \"{g}\"')
--   "
--
-- Snapshot: 21 invariants across 5 guarded surfaces
-- Verified: 5/5 surfaces have >= 1 CRITICAL (violation_sort = bottom symbol)

-- ── SurfaceInvariant structure ────────────────────────────────────────────────

structure SurfaceInvariant where
  name           : String
  violation_sort : String   -- "⊥" = CRITICAL (hard bottom); "" or other = HIGH/MEDIUM
  guards         : String   -- guard surface path (e.g. "governance/SYSTEM.yaml")
  deriving DecidableEq, Repr

-- ── allInvariants — snapshot of simon.surface_invariants.v1 ─────────────────
-- Generated from fsl/SYSTEM.yaml at MISSION-LEAN-INV-COMPLETENESS build time.
-- 21 invariants total; 14 CRITICAL (violation_sort = "⊥").

def allInvariants : List SurfaceInvariant := [
  -- analysis/SYSTEM.yaml (1 invariant, 1 CRITICAL)
  ⟨"scan_output_read_only",              "⊥", "analysis/SYSTEM.yaml"⟩,
  -- constitution/SYSTEM.yaml (7 invariants, 3 CRITICAL)
  ⟨"constitutional_surface_immutable",   "⊥", "constitution/SYSTEM.yaml"⟩,
  ⟨"constitutional_lipschitz_bounded",   "",  "constitution/SYSTEM.yaml"⟩,
  ⟨"surface_registry_consistent",        "⊥", "constitution/SYSTEM.yaml"⟩,
  ⟨"amendment_lineage_complete",         "",  "constitution/SYSTEM.yaml"⟩,
  ⟨"fsl_expression_admissibility",       "",  "constitution/SYSTEM.yaml"⟩,
  ⟨"file_inspector_read_only",           "⊥", "constitution/SYSTEM.yaml"⟩,
  ⟨"inspector_output_bounds_builder",    "",  "constitution/SYSTEM.yaml"⟩,
  -- formatnode/docs/SYSTEM.yaml (5 invariants, 4 CRITICAL)
  ⟨"system_yaml_governed_writes",        "⊥", "formatnode/docs/SYSTEM.yaml"⟩,
  ⟨"system_yaml_append_only_modules",    "⊥", "formatnode/docs/SYSTEM.yaml"⟩,
  ⟨"identity_chain_immutable",           "⊥", "formatnode/docs/SYSTEM.yaml"⟩,
  ⟨"policy_engine_no_self_modify",       "⊥", "formatnode/docs/SYSTEM.yaml"⟩,
  ⟨"policy_engine_fails_open_on_empty_policy", "", "formatnode/docs/SYSTEM.yaml"⟩,
  -- governance/SYSTEM.yaml (7 invariants, 5 CRITICAL)
  ⟨"governance_truth_surface_immutable", "⊥", "governance/SYSTEM.yaml"⟩,
  ⟨"mission_log_append_only",            "⊥", "governance/SYSTEM.yaml"⟩,
  ⟨"roles_exclusive_per_response",       "",  "governance/SYSTEM.yaml"⟩,
  ⟨"packet_authorizes_build",            "⊥", "governance/SYSTEM.yaml"⟩,
  ⟨"governed_network",                   "⊥", "governance/SYSTEM.yaml"⟩,
  ⟨"state_proof_immutable",              "⊥", "governance/SYSTEM.yaml"⟩,
  ⟨"self_reflection_immutable",          "",  "governance/SYSTEM.yaml"⟩,
  -- governance/stability/coherence_engine.py (1 invariant, 1 CRITICAL)
  ⟨"floor_bound",                        "⊥", "governance/stability/coherence_engine.py"⟩
]

-- ── Derived: guarded surfaces ────────────────────────────────────────────────
-- The 5 distinct guard paths present in allInvariants.
-- Order is the first-appearance order from allInvariants.

def guardedSurfaces : List String :=
  ["analysis/SYSTEM.yaml",
   "constitution/SYSTEM.yaml",
   "formatnode/docs/SYSTEM.yaml",
   "governance/SYSTEM.yaml",
   "governance/stability/coherence_engine.py"]

-- ── Sanity: counts ────────────────────────────────────────────────────────────

def totalInvariants  : Nat := allInvariants.length           -- 21
def criticalCount    : Nat :=
  (allInvariants.filter (·.violation_sort == "⊥")).length    -- 14
def surfaceCount     : Nat := guardedSurfaces.length          -- 5
